import Head from "next/head";
import styles from "../styles/Home.module.css";
import Bubbles from "../components/bubbles";
import styled from "@emotion/styled";
import { useEffect, useState } from "react";
import Script from "next/script";

const AdsDiv = styled.div`
  background-color: grey;
  position: relative;
  z-index: 11111;
`;

export default function Home() {
  return (
    <>
      <Head>
        <title>Axmaze.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AdsDiv>
        <ins
          className="adsbygoogle"
          style={{ display: "block" }}
          data-ad-client="ca-pub-8467103316925015"
          data-ad-slot="4969098561"
          data-ad-format="auto"
          data-full-width-responsive="true"
        ></ins>
        <Script id="script1">
          (adsbygoogle = window.adsbygoogle || []).push({});
        </Script>
      </AdsDiv>

      <div>
        <Bubbles />
      </div>

      <AdsDiv>
        <ins
          className="adsbygoogle"
          style={{ display: "inline-block", width: "728px", height: "90px" }}
          data-ad-client="ca-pub-8467103316925015"
          data-ad-slot="8716771880"
        ></ins>
        <Script id="script2">
          (adsbygoogle = window.adsbygoogle || []).push({});
        </Script>
      </AdsDiv>
    </>
  );
}
